server :
  port : 3000

spring :
  mvc:
    view:
      suffix: .html

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  h2:
    console:
      enabled: true